ADPUPA prepbufr python/json updates (#793)
A number of changes were made to the adpupa python script and json file:

- TPC flags are changed for the airTemperature and virtualTemperature
- Group and type are changed for the height variable
- Variable verticalSignificance is changed to the
prepbufrDataLevelCategory
- Updated input/output file names in python script and some information
in json file

**Variable naming convention results:** 

  Variable MetaData/prepbufrDataLevelCategory
ERROR: Variable 'MetaData/prepbufrDataLevelCategory' is not listed in
the YAML conventions file.
  Variable QCFlags/qualityFlags
  Variable ObsValue/stationPressure
  Variable ObsValue/airTemperature
  Variable ObsValue/virtualTemperature
  Variable ObsValue/specificHumidity
  Variable ObsValue/windEastward
  Variable ObsValue/windNorthward
  Variable QualityMarker/pressure
  Variable QualityMarker/stationPressure
  Variable QualityMarker/airTemperature
  Variable QualityMarker/windEastward
  Variable QualityMarker/virtualTemperature
  Variable QualityMarker/specificHumidity
  Variable QualityMarker/windNorthward

**Final results:**
  _errors:      1_
  _warnings:    0_

A new variable MetaData/prepbufrDataLevelCategory will be added to the
YAML conventions file.

---------

Co-authored-by: PraveenKumar-NOAA <Praveen.Kumar@noaa.gov>